config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stocks#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :stocks, only: [:index,:new,:show,:create,:edit,:update,:destroy]
   get 'groups' => "groups#index"
   post '/stocks/:id/edit' => "stocks#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do  
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json'}
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :users, optional: true

  validates :name, :count, presence: true
  validates :name, uniqueness: true

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :login_required

  def index
    @users = User.all
    @stocks =Stock.all
  end
  
  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    if @stock.save
      redirect_to root_path
      return
    else
      flash.now[:alert] = '追加できませんでした'
      render :new
    end
  end

  def show
    stocks = stock_url(params[:id])
    @stocks = Stock.all
  end


  def edit
    @stocks = Stock.find(params[:id])
  end

  def update
    @stocks = Stock.find(params[:id])
    @stocks.update(update_params)
    redirect_to root_path
  end 

  def destroy
    @stock = Stock.find(params[:id])
    if @stock.destroy
      redirect_to root_path
    end
  end
  private

  def login_required 
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to new_user_session_path
    end
  end

  def update_params
    params.permit(:count)
  end

  def stock_params
    params.require(:stock).permit(:name,:count)
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_add.html.haml
.primal
  .primal__top
    STOCK-APP 商品追加
    
  .add
    .add__area
      追加する商品名を入力してください
    .add-form__text
      = form_with model: @stock do |f|
        .add-form__text__stock__item
          = f.text_field :name, placeholder: "商品名を入力" 
          = f.number_field :count, placeholder: "在庫数を入力" 
          = f.submit '以上の商品を追加', class: 'form-decide__btn'

app/views/stocks/_cal-item.html.haml
.primal
  .primal__top
    STOCK-APP 入荷・出荷

  .add
    .add__area
      =@stocks.name
      .add__area__text
        の在庫数を更新
  
    %table
      %tbody
        %tr
          %th.stock
            現在の在庫数
          %th.shipment
            在庫数の更新

        %tr
          %td
            =@stocks.count
          %td
            =form_with model: @stock,url: stock_path,method: :put do |f|
              =f.number_field :count , placeholder: "新規の在庫数"
              =f.submit "更新する"
                


      

app/views/stocks/_cancel.html.haml
.primal
  .primal__top
    STOCK-APP 商品取消

  .items-table
    .items-table__head
      商品一覧
    %table
      %tbody
        %tr
          %th.name
            商品名
          %th.stock
            在庫数
          %th.del
            取消

      - @stocks.each do |stock|
        %tr
          %td
            =stock.name
          %td
            =stock.count
          %td
            =link_to "取消",stock_path(stock.id), method: :delete, data: { confirm: '削除してよろしいですか?' }, id: :cancel
      

app/views/stocks/_items.html.haml
.primal
  .primal__top
    STOCK-APP 入荷・出荷

  .items-table
    .items-table__head
      商品一覧
    %table
      %tbody
        %tr
          %th.name
            商品名
          %th.stock
            在庫数
          %th.inc-dec
            在庫数の変更
      - @stocks.each do |stock|
        %tr.items-data
          %td
            =stock.name
          %td#stock-origin
            =stock.count
          %td
            =link_to "更新",edit_stock_path(stock.id),id: :stock_update

app/views/stocks/_links.html.haml
.top-side
  .side-menu
    %ul.side-menu__names
      %li.side-menu__names__user
        =current_user.store
      %li.side-menu__names__user
        =current_user.name

  .menu
    .menu__top
      メニュー
      %ul.menu__top__lists
        %li.menu__top__lists__links
          = link_to "在庫一覧",root_path,class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          = link_to "商品追加",new_stock_path,class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          = link_to "商品取消",stock_path(:id),class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          = link_to "チャット",groups_path,class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          = link_to "メアド編集",edit_user_path(current_user) ,class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          =link_to "ログアウト", users_sign_out_path,class: "menu__top__lists__links__btn",id: "logout"
  

app/views/stocks/edit.html.haml
.container
  = render "links"
  = render "cal-item"

app/views/stocks/index.html.haml
.container
  = render "links"
  = render "items"

app/views/stocks/new.html.haml
.container
  = render "links"
  = render "add"

      

    

app/views/stocks/show.html.haml
.container
  = render "links"
  = render "cancel"